config/routes.rb
Rails.application.routes.draw do

  resources :bill_tables
  resources :guard_infos    
  resources :quotation_details
  resources :sender_details
  resources :gen_avails
  resources :gen_expenses
  resources :gen_details
  resources :third_party_providers
  resources :taxes

  root 'welcome#index'
  get  "dashboard"        => "client_details#dashboard"
  post "dashboard"	 => "client_details#dashboard"
  get  "client"           => "client_details#index"
  post "client"		        => "client_details#index"
  get  "clientdetails"    => "client_details#new"
  post "clientdetails"    => "client_details#new"
  get  "quotations/:id"   => "client_details#quotations"
  get "closed/client_details/:id" => "quotation_details#contractClose"
  get "opened/client_details/:id" => "quotation_details#contractOpen"
  post "closed/client_details/:id" => "quotation_details#contractClose"
  post "opened/client_details/:id" => "quotation_details#contractOpen"
  get  "sender"           => "sender_details#index"
  post "sender"		        => "sender_details#index"
  get  "senderdetails"    => "sender_details#new"
  post "senderdetails"    => "sender_details#new"
  get  "generators"       => "gen_details#index"
  get  "gendetails"       => "gen_details#new"
  post "gendetails"       => "gen_details#new"
  get  "genexpenses"      => "gen_expenses#index"
  get  "expenses"         => "gen_expenses#new" 
  post "expenses"         => "gen_expenses#new"  
  get  "quotationviewer"  => "quotation_details#index"
  get  "thirdparty"       => "third_party_providers#index"
  get  "providers"        => "third_party_providers#new"
  post "providers"        => "third_party_providers#new"
  get  "welcomemail"      => "client_details#mail"
  get  "sendpdfmail/:id"  => "quotation_details#mail"  
  get  "notice"           => "quotation_details#notice"
  get  "availableGenerators"     => "gen_avails#new"
  post "availableGenerators"     => "gen_avails#new"
  get  "/approved/quotation_details/:id" => "quotation_details#approve"
  post "/approved/quotation_details/:id" => "quotation_details#approve"

  devise_for :users
    as :user do
      get 'login'               => 'devise/sessions#new'
      post 'login'              => 'devise/sessions#create'
      get 'logout'              => 'devise/sessions#destroy'
      get 'register'            => 'devise/registrations#new'
      get 'registered'          => 'devise/registrations#show'
      get 'passwordReset'       => 'devise/passwords#new'
      get 'changePassword'      => 'devise/passwords#edit'  
      get 'resendConfirmation'  => 'devise/confirmations#new'    
    end

  mount Mercury::Engine => '/'

  resources :client_details do
    member { post :clientUpdate }
  end

  resources :fake_quotations do
    member { post :mercury_update}
  end

  namespace :mercury do
    resources :images
  end
 
  get "*path" => "quotation_details#notfound"      

end

app/models/bill_table.rb
class BillTable < ActiveRecord::Base
  belongs_to :quotation
end

app/models/client_detail.rb
class ClientDetail < ActiveRecord::Base
  belongs_to :sender_detail
  has_many :quotation

  
  validates_presence_of :contactNo
  validates_format_of :contactNo, with: /[0-9]/
  validates_length_of :contactNo, :maximum =>12, :minimum => 4

  validates_presence_of :sender_details_id
end

app/models/client_gen_set.rb
class ClientGenSet < ActiveRecord::Base
  belongs_to :quotation_detail
  belongs_to :client_detail
  belongs_to :gen_avail
  belongs_to :gaurd_detail
  belongs_to :third_party_gen
end

app/models/fake_quotation.rb
class FakeQuotation < ActiveRecord::Base
  belongs_to :client_details
  belongs_to :sender_details

  protokoll :referenceNumber, :pattern => "AEQF%y###"  
end

app/models/gaurd_detail.rb
class GaurdDetail < ActiveRecord::Base
end

app/models/gen_avail.rb
class GenAvail < ActiveRecord::Base

  validates_presence_of :gen_detail_id
  belongs_to :gen_detail
  protokoll :genID, :pattern => "G%y###"

end

app/models/gen_detail.rb
class GenDetail < ActiveRecord::Base
  
  validates_format_of :genRent, with: /[0-9]/, :message => "accepts Numbers only"
  validates_format_of :totalGen, with: /[0-9]/, :message => "accepts Numbers only"

  has_many :gen_avails	
end

app/models/gen_expense.rb
class GenExpense < ActiveRecord::Base
  belongs_to :client_detail
  
  validates_presence_of :readingBy
end

app/models/quotation_detail.rb
class QuotationDetail < ActiveRecord::Base
  belongs_to :client_detail
  belongs_to :sender_detail

  protokoll :referenceNumber, :pattern => "AE%y###"
end 

app/models/quotation_rent.rb
class QuotationRent < ActiveRecord::Base
  belongs_to :client_detail
  belongs_to :quotation_detail
end

app/models/sender_detail.rb
class SenderDetail < ActiveRecord::Base
  has_attached_file :signature, :styles => { :small => "150x150>", med: "200x200", large: "300x300"},
                    :url  => "/assets/sender_signature/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/sender_signature/:id/:style/:basename.:extension"
  validates_attachment_presence :signature
  validates_attachment :signature, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

 
  validates_presence_of :contactNo
  validates_format_of :contactNo, with: /[0-9]/
  validates_length_of :contactNo, :maximum =>12, :minimum => 4

  validates_presence_of :quotationType
end

app/models/tax.rb
class Tax < ActiveRecord::Base
end

app/models/third_party_gen.rb
class ThirdPartyGen < ActiveRecord::Base
  
  belongs_to :third_party_provider

  protokoll :genID, :pattern => "TP###"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/bill_tables_controller.rb
class BillTablesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bill_table, only: [:show, :edit, :update, :destroy]

  # GET /bill_tables
  # GET /bill_tables.json
  def index
    @bill_tables = BillTable.all
  end

  # GET /bill_tables/1
  # GET /bill_tables/1.json
  def show
  end

  # GET /bill_tables/new
  def new
    @bill_table = BillTable.new
  end

  # GET /bill_tables/1/edit
  def edit
  end

  # POST /bill_tables
  # POST /bill_tables.json
  def create
    @bill_table = BillTable.new(bill_table_params)

    respond_to do |format|
      if @bill_table.save
        format.html { redirect_to @bill_table, notice: 'Bill table was successfully created.' }
        format.json { render :show, status: :created, location: @bill_table }
      else
        format.html { render :new }
        format.json { render json: @bill_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bill_tables/1
  # PATCH/PUT /bill_tables/1.json
  def update
    respond_to do |format|
      if @bill_table.update(bill_table_params)
        format.html { redirect_to @bill_table, notice: 'Bill table was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill_table }
      else
        format.html { render :edit }
        format.json { render json: @bill_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bill_tables/1
  # DELETE /bill_tables/1.json
  def destroy
    @bill_table.destroy
    respond_to do |format|
      format.html { redirect_to bill_tables_url, notice: 'Bill table was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill_table
      @bill_table = BillTable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_table_params
      params.require(:bill_table).permit(:bill_id, :monthly_rent, :mail_sent, :third_party_payment, :owner_payment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bill_tables_helper.rb
module BillTablesHelper
end

app/helpers/gen_avails_helper.rb
module GenAvailsHelper
end

app/helpers/gen_details_helper.rb
module GenDetailsHelper
end

app/helpers/gen_expenses_helper.rb
module GenExpensesHelper
end

app/helpers/taxes_helper.rb
module TaxesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bill_tables/_form.html.erb
<%= form_for(@bill_table) do |f| %>
  <% if @bill_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill_table.errors.count, "error") %> prohibited this bill_table from being saved:</h2>

      <ul>
      <% @bill_table.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bill_id %><br>
    <%= f.number_field :bill_id %>
  </div>
  <div class="field">
    <%= f.label :monthly_rent %><br>
    <%= f.text_field :monthly_rent %>
  </div>
  <div class="field">
    <%= f.label :mail_sent %><br>
    <%= f.text_field :mail_sent %>
  </div>
  <div class="field">
    <%= f.label :third_party_payment %><br>
    <%= f.text_field :third_party_payment %>
  </div>
  <div class="field">
    <%= f.label :owner_payment %><br>
    <%= f.text_field :owner_payment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bill_tables/edit.html.erb
<h1>Editing Bill Table</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill_table %> |
<%= link_to 'Back', bill_tables_path %>

app/views/bill_tables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bill Tables</h1>

<table>
  <thead>
    <tr>
      <th>Bill</th>
      <th>Monthly rent</th>
      <th>Mail sent</th>
      <th>Third party payment</th>
      <th>Owner payment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bill_tables.each do |bill_table| %>
      <tr>
        <td><%= bill_table.bill_id %></td>
        <td><%= bill_table.monthly_rent %></td>
        <td><%= bill_table.mail_sent %></td>
        <td><%= bill_table.third_party_payment %></td>
        <td><%= bill_table.owner_payment %></td>
        <td><%= link_to 'Show', bill_table %></td>
        <td><%= link_to 'Edit', edit_bill_table_path(bill_table) %></td>
        <td><%= link_to 'Destroy', bill_table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bill table', new_bill_table_path %>

app/views/bill_tables/new.html.erb
<h1>New Bill Table</h1>

<%= render 'form' %>

<%= link_to 'Back', bill_tables_path %>

app/views/bill_tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bill:</strong>
  <%= @bill_table.bill_id %>
</p>

<p>
  <strong>Monthly rent:</strong>
  <%= @bill_table.monthly_rent %>
</p>

<p>
  <strong>Mail sent:</strong>
  <%= @bill_table.mail_sent %>
</p>

<p>
  <strong>Third party payment:</strong>
  <%= @bill_table.third_party_payment %>
</p>

<p>
  <strong>Owner payment:</strong>
  <%= @bill_table.owner_payment %>
</p>

<%= link_to 'Edit', edit_bill_table_path(@bill_table) %> |
<%= link_to 'Back', bill_tables_path %>