config/routes.rb
Rails.application.routes.draw do

  resources :bill_tables
  resources :guard_infos    
  resources :quotation_details
  resources :sender_details
  resources :gen_avails
  resources :gen_expenses
  resources :gen_details
  resources :third_party_providers
  resources :taxes

  root 'welcome#index'
  get  "dashboard"        => "client_details#dashboard"
  post "dashboard"	 => "client_details#dashboard"
  get  "client"           => "client_details#index"
  post "client"		        => "client_details#index"
  get  "clientdetails"    => "client_details#new"
  post "clientdetails"    => "client_details#new"
  get  "quotations/:id"   => "client_details#quotations"
  get "closed/client_details/:id" => "quotation_details#contractClose"
  get "opened/client_details/:id" => "quotation_details#contractOpen"
  post "closed/client_details/:id" => "quotation_details#contractClose"
  post "opened/client_details/:id" => "quotation_details#contractOpen"
  get  "sender"           => "sender_details#index"
  post "sender"		        => "sender_details#index"
  get  "senderdetails"    => "sender_details#new"
  post "senderdetails"    => "sender_details#new"
  get  "generators"       => "gen_details#index"
  get  "gendetails"       => "gen_details#new"
  post "gendetails"       => "gen_details#new"
  get  "genexpenses"      => "gen_expenses#index"
  get  "expenses"         => "gen_expenses#new" 
  post "expenses"         => "gen_expenses#new"  
  get  "quotationviewer"  => "quotation_details#index"
  get  "thirdparty"       => "third_party_providers#index"
  get  "providers"        => "third_party_providers#new"
  post "providers"        => "third_party_providers#new"
  get  "welcomemail"      => "client_details#mail"
  get  "sendpdfmail/:id"  => "quotation_details#mail"  
  get  "notice"           => "quotation_details#notice"
  get  "availableGenerators"     => "gen_avails#new"
  post "availableGenerators"     => "gen_avails#new"
  get  "/approved/quotation_details/:id" => "quotation_details#approve"
  post "/approved/quotation_details/:id" => "quotation_details#approve"

  devise_for :users
    as :user do
      get 'login'               => 'devise/sessions#new'
      post 'login'              => 'devise/sessions#create'
      get 'logout'              => 'devise/sessions#destroy'
      get 'register'            => 'devise/registrations#new'
      get 'registered'          => 'devise/registrations#show'
      get 'passwordReset'       => 'devise/passwords#new'
      get 'changePassword'      => 'devise/passwords#edit'  
      get 'resendConfirmation'  => 'devise/confirmations#new'    
    end

  mount Mercury::Engine => '/'

  resources :client_details do
    member { post :clientUpdate }
  end

  resources :fake_quotations do
    member { post :mercury_update}
  end

  namespace :mercury do
    resources :images
  end
 
  get "*path" => "quotation_details#notfound"      

end

app/models/client_detail.rb
class ClientDetail < ActiveRecord::Base
  belongs_to :sender_detail
  has_many :quotation

  
  validates_presence_of :contactNo
  validates_format_of :contactNo, with: /[0-9]/
  validates_length_of :contactNo, :maximum =>12, :minimum => 4

  validates_presence_of :sender_details_id
end

app/controllers/client_details_controller.rb
class ClientDetailsController < ApplicationController
  before_action :authenticate_user!

  def index
    @client_details = ClientDetail.all
    @sender_details = SenderDetail.all
    @quotations     = QuotationDetail.all
    @fakeQuotations = FakeQuotation.all
  end

  def show
    @quotation_detail = QuotationDetail.find(params[:id])
    @client_detail = ClientDetail.find(@quotation_detail.client_details_id)
    @sender_detail = SenderDetail.find(@quotation_detail.sender_details_id)

    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => 'Quotation',
        :template => 'client_details/mail.pdf.erb',
        :layout => 'pdf.html.erb',       
        :page_size => 'A4',
        :show_as_html => params[:debug].present?
      end       
    end

  end

  def new
    @client_detail = ClientDetail.new
  end

  def notice
  end

  def mail
  end

  def edit
    @client_detail = ClientDetail.find(params[:id])
  end

  def create
    @client_detail = ClientDetail.new(client_detail_params)
	  @gen = GenDetail.all
    @types = Array.new	
	  @rents = Array.new

    @gen.each do|gen|
		  type = gen.genType
  		rent = gen.genRent
	  	@types.push(type)
  		@rents.push(rent)
    end

    types = @types.join(",")
  	rents = @rents.join(",")

    if @client_detail.save

      @sender_detail = SenderDetail.find(@client_detail.sender_details_id)

      if (@sender_detail.quotationType == "Real")

        @quotation_detail = QuotationDetail.new()
        @quotation_detail.sender_details_id = @client_detail.sender_details_id
        @quotation_detail.client_details_id = @client_detail.id
        @quotation_detail.save

        @qtn_rent = QuotationRent.new()
  		  @qtn_rent.genType = types
        @qtn_rent.genRent = rents
        @qtn_rent.client_detail_id = @client_detail.id
        @qtn_rent.quotation_detail_id = @quotation_detail.id
        @qtn_rent.save      
        
        redirect_to quotation_detail_path(@quotation_detail.id)
      
      else
        
        @fake_quotation = FakeQuotation.new()
        @fake_quotation.sender_details_id = @client_detail.sender_details_id
        @fake_quotation.client_details_id = @client_detail.id
        @fake_quotation.save
        
        redirect_to fake_quotation_path(@fake_quotation.id)
      end
	
    else
      render "new"
    end
  end
  
  def quotations	
    @client_details = ClientDetail.find(params[:id])
    @quotations = QuotationDetail.where(client_details_id: params[:id])
  end

  def clientUpdate
    @client_detail = ClientDetail.find(params[:id])
    if @client_detail.mailStatus == true	
		  if @client_detail.save
			 @quotation_detail = QuotationDetail.new()
			 @quotation_detail.sender_details_id = @client_detail.sender_details_id
			 @quotation_detail.client_details_id = @client_detail.id
			 @quotation_detail.save
	   end
    elsif @client_detail.mailStatus == false
    	if @client_detail.update(client_detail_params)
      	redirect_to action: 'index'
    	else
      	render 'edit'
    	end    
  	end
  end

  def update

    @quotation_detail = QuotationDetail.where(client_details_id: params[:id])
    @quotation_detail.each do |quotation|
    quotation.subject = params[:content][:quotation_subject][:value]
    quotation.regard = params[:content][:quotation_regard][:value]    
    quotation.regardContent = params[:content][:quotation_regardContent][:value]
    quotation.bankZoneOne = params[:content][:quotation_bankZoneOne][:value]
    quotation.bankZoneTwo = params[:content][:quotation_bankZoneTwo][:value]
    quotation.bankNameOne = params[:content][:quotation_bankNameOne][:value]
    quotation.bankNameTwo = params[:content][:quotation_bankNameTwo][:value]
    quotation.bankNameThree = params[:content][:quotation_bankNameThree][:value]
    quotation.bankNameFour = params[:content][:quotation_bankNameFour][:value]
    quotation.bankNameFive = params[:content][:quotation_bankNameFive][:value]
    quotation.quotationLine  = params[:content][:quotation_quotationLine][:value]
    quotation.quotationRateList = params[:content][:quotation_quotationRateList][:value] 
    quotation.contentPartOne = params[:content][:quotation_contentPartOne][:value] 
    quotation.contentPartTwo = params[:content][:quotation_contentPartTwo][:value]
    quotation.thankYou = params[:content][:quotation_thankYou][:value]
    quotation.yoursTruly = params[:content][:quotation_yoursTruly][:value]
    quotation.nameOfCompany = params[:content][:quotation_nameOfCompany][:value]
    quotation.emailIdOne = params[:content][:quotation_emailIdOne][:value]
    quotation.emailIdTwo = params[:content][:quotation_emailIdTwo][:value]
    quotation.emailIdThree = params[:content][:quotation_emailIdThree][:value]
    quotation.emailIdFour = params[:content][:quotation_emailIdFour][:value]
    quotation.contactNumberOne = params[:content][:quotation_contactNumberOne][:value]
    quotation.contactNumberTwo = params[:content][:quotation_contactNumberTwo][:value]
    quotation.contactNumberThree = params[:content][:quotation_contactNumberThree][:value]

    quotation.save!

    end

    render text: ''
  end

  private

  def client_detail_params
    params.require(:client_detail).permit(:designation, :nameOfBank, :address, :district, :contactNo, :emailID, :sender_details_id, :approved)
  end

end

app/helpers/client_details_helper.rb
module ClientDetailsHelper
end

app/views/client_details/dashboard.html.erb
<section class="dashboard" style="overflow:hidden; display:block;">
    <%= render 'welcome/header' %>
    <main>
        <div class="icon1">
            <div class="image1"></div>	
            <p class="textIcon1" style="text-align:center"><%= link_to "Sender Details", sender_path, {:class=>"link-color"} %></p>         
        </div>
        <div class="icon2">
            <div class="image2"></div>
           <p class="textIcon2" style="text-align:center"><%= link_to "Generator Details", generators_path, {:class=>"link-color"} %></p>
        </div>
        <div class="icon3">
            <div class="image3"></div>
           <p class="textIcon3" style="text-align:center"><%= link_to "New Client", clientdetails_path, {:class=>"link-color"} %></p>
                   </div>
        <div style="clear:both"></div>
        <div class="icon4">
           <div class="image4"></div>
            <p class="textIcon4" style="text-align:center"><%= link_to "Quotation Viewer", client_path, {:class=>"link-color"} %></p>
        </div>
        <div class="icon5"> 
            <div class="image5"></div>
            <p class="textIcon5" style="text-align:center"><%= link_to "Generator Expenses", genexpenses_path, {:class=>"link-color"} %></p>
        </div>        
        <div class="icon6">
            <div class="image6"></div>
            <p class="textIcon6" style="text-align:center"><%= link_to "Third Party Provider", thirdparty_path, {:class=>"link-color"} %></p>            
        </div>        
    </main>
</section>

app/views/client_details/edit.html.erb
<!-- CSS on this form is forked from quotations CSS which is in quotation.css.scss -->

<section class="quotationSection">
    <%= render "welcome/header"  %>
    <div class="quotationForm">
    <h2 class="fillForm">Client Details</h2>
    <%= form_for :client_detail, url: {action: 'clientUpdate'} do |f| %>
	
  <% if @client_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client_detail.errors.count, "error") %> prohibited this gen_detail from being saved:</h2>

      <ul>
      <% @client_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <label class="ll">Designation</label> <%= f.text_field :designation, autofocus: true, :required => true, :class => 'nameOfPerson', :placeholder => 'Designation', :title => 'Name of Person' %><br>
  <label class="ll">Bank Name</label>         <%= f.text_field :nameOfBank, autofocus: true, :required => true, :class => 'nameOfBank', :placeholder => 'Name of Bank', :title => 'Name of Bank' %><br>
         <label class="ll">Address</label>  <%= f.text_field :address, autofocus: true, :required => true, :class => 'address', :placeholder => 'Address', :title => 'Address' %><br>
         <label class="ll">City</label>  <%= f.text_field :district, autofocus: true, :required => true, :class => 'district', :placeholder => 'District / City', :title => 'District / City' %><br>
      <label class="ll">Contact No.</label>     <%= f.text_field :contactNo, autofocus: true, :required => true, :class => 'contactNumber', :placeholder => 'Contact Number', :title => 'Contact Number' %><br>
     <label class="ll">Email</label>      <%= f.email_field :emailID, autofocus: true, :required => true, :class => 'eMail', :placeholder => 'E-mail', :title => 'Email Id of Sender' %><br>
       <%= f.collection_select :sender_details_id, SenderDetail.all, :id, :name, prompt: true, autofocus: true, :class => 'dropDown new-dropdown' %>
          <p style="text-align: center;"><%= f.submit :class => 'quotation_submit', :value => 'Save', :disabled => false, :disable_with => "Please wait..." %></p><br>
        <% end %>
    </div> 
</section>

app/views/client_details/fakeQuotation.html.erb
<%= render 'welcome/header' %> <br><br><br><br><br>
<table id="clients-quotations" class="display responsive no-wrap">
  <thead>
    <tr>
      <th>Reference Number</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Mail Staus</th>
    </tr>
  </thead>

  <tbody>
      <% @fakeQuotations.each do |q| %>
        <% if q.client_details_id == @client_details.id %>
        <tr>
          <td><%= q.referenceNumber %></td>
          <td><%= link_to "Show", quotation_detail_path(q.id) %></td>
          <td><%= link_to "Edit", "/editor" + quotation_detail_path(q.id) %></td> 
            <% if q.mailStatus == true %>               
              <td>Sent</td>
            <% else %>
             <td>Draft</td>
            <% end %>
        </tr>    
        <% end %>
      <% end %>
  </tbody>
</table>

<script>
    $(document).ready(function() {
    $('#clients-quotations').dataTable({
      responsive: true
    });
  } );
</script>

app/views/client_details/index.html.erb
<%= render 'welcome/header' %> <br><br><br><br><br>

<div class="container">
<h2 class="table-heading">Real Quotations</h2>



<table id="realQuotations" class="display responsive no-wrap">

  <thead>
    <tr>
      <th>Sender Name</th>
      <th>Bank Name</th>
      <th>District</th>      
      <th>Contact Number</th>
      <th>Email ID</th>
      <th>Show Quotations</th>
      <th>Edit Client</th>
      <th>Approve</th>    
      <th>Contract</th> 
    </tr>
  </thead>  

  <tbody>
  <% @sender_details.each do |s| %>
    <% if s.quotationType == "Real" %>
      <% @client_details = ClientDetail.where(sender_details_id: s.id) %>
      <% @client_details.each do |f| %>    
        <tr>
          <td><%= s.name %></td>
          <td><%= f.nameOfBank %></td>
          <td><%= f.district %></td>      
          <td><%= f.contactNo %></td>
          <td><%= f.emailID %></td> 
          <td><%= link_to "Show", "/quotations/" + f.id.to_s %></td>
          <td><%= link_to "Edit", client_detail_path(f.id) + "/edit"  %></td>    
          <% if f.approved == true %> 
            <td>Approved</td>
          <% else %>
            <td><%= button_to 'E-mail Pending', "/approved" + quotation_detail_path(f.id) %></td>
          <% end %>      
          <% if f.contract == true %>
            <td><%= button_to  'Close', "/closed" + client_detail_path(f.id) %></td> 
          <% else %>
            <td><%= button_to "Open", "/opened" + client_detail_path(f.id) %></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  <% end %>  
  </tbody>

</table> <br><br>
<h2 class="table-heading">Fake Quotations</h2>


<table id="fakeQuotations" class="display responsive no-wrap">

  <thead>
    <tr>
      <th>Sender Name</th>
      <th>Bank Name</th>
      <th>District</th>      
      <th>Contant Number</th>
      <th>Email ID</th>
      <th>Show Quotations</th>
      <th>Edit Client</th>
    </tr>
  </thead>  

  <tbody>
  <% @sender_details.each do |s| %>
    <% if s.quotationType == "Fake" %>
      <% @client_details = ClientDetail.where(sender_details_id: s.id) %>
      <% @client_details.each do |f| %>    
         <% 
          @fake_qtn = FakeQuotation.where(client_details_id: f.id)
          qtn_id = ''
          @fake_qtn.each do |q|
            qtn_id = q.id
          end
        %>
      <tr>
        <td><%= s.name%></td>          
        <td><%= f.nameOfBank %></td>
        <td><%= f.district %></td>      
        <td><%= f.contactNo %></td>
        <td><%= f.emailID %></td> 
        <td><%= link_to "Show", "/fake_quotations/" + qtn_id.to_s %></td>
        <td><%= link_to "Edit", client_detail_path(f.id) + "/edit"  %></td>
        <% end %>  
      </tr>
    <% end %>  
  <% end %>
  </tbody>

</table>
</div>


<script>
    $(document).ready(function() {
    $('#realQuotations').dataTable({
      responsive: true
    });
  } );
</script>

<script>
    $(document).ready(function() {
    $('#fakeQuotations').dataTable({
      responsive: true
    });
  } );
</script>

app/views/client_details/mail.html.erb
<h1>your mail has been sent</h1>

app/views/client_details/mail.pdf.erb
<section class="quotationPagePdf" style="width: 820px; margin: auto;">
<div class="whiteOne">

        <h2 class="amrit">AMRIT</h2>
        <h2 class="engg">E N G I N E E R S</h2>
        
        <!--        <img src="/images/amrit_logo.png"/> -->
    </div>
    <div class="blue">
        <h2 class="offer">Offering Rental Gensets</h2>
        <h2 class="basis">on Monthly Basis</h2>
    </div>
    <div class="greyOne">
        <h3 class="serviceTax">Service Tax No.: APRPK1196BSD001</h3>
        <!--        <h3 class="date">Dated : <%= Time.now.strftime("%m/%d/%Y") %></h3>-->
    </div>
    <div class="whiteTwo">
        <div class="phone">
            <h3 class="phoneText">Phone</h3>
            <p class="phoneNumber"> +91 98140-09500 <br />
                                    +91 87270-09500 <br /> 
                                    +91 161-2439500 <br />
            </p>
        </div>
        <div class="email">
            <h3 class="emailText">Email</h3>
            <p class="emailAddress"> ishnoorsingh@in.com <br />
                                     jasvirsinghsond@gmail.com <br /> 
                                     amritengineers80@gmail.com<br />
                                     amritengineers@yahoo.in <br /> 
            </p>            
        </div>
        <div class="website">
            <h3 class="websiteText">Website</h3>
            <p class="websiteAddress">http://Sample.com<br />
            </p>            
        </div>
    </div>

    <div class="greyTwo">
        <h3 class="headOffice"><span>Head Office:</span> # 1380, St. No. 31, Janta Nagar, Bhagwan Chowk, Near Public Health Center, Ludhiana-141003. Punjab</h3>
        <h3 class="subOffice"><span>Sub Office:</span> # 48, Wadda Gurdwara Sahib Market, Opp. G.N.E, College, Near Octroi Post, Gill Road, Ludhiana</h3>
    </div>

    <!-- Template Start -->
    <!-- To-From Part Start -->
    <div class="contentPartPdf">
        <div class="contentsToStatementPdf">To</div><br />
        <div class="detailsPdf"><%= @client_detail.designation.html_safe  %>, <br><%= @client_detail.nameOfBank.html_safe  %>, <br> <%= @client_detail.address.html_safe  %>, <br><%= @client_detail.district.html_safe  %></div> <br />
        <div class="subjectPdf"><%= @quotation_detail.subject.html_safe %></div> <br />
        <div class="regardsPdf"><%= @quotation_detail.regard.html_safe  %></div>
        <div class="regardContentPdf"><%= @quotation_detail.regardContent.html_safe  %></div><br>
    </div>    
    <!-- To-From Part End -->
    <!--  Banks Names Start Here -->

    <div class="banksPdf" >
        <table class="tg">
          <tr>
            <th class="tg-hgcj">Bank</th>
            <th class="tg-hgcj">Location</th>
          </tr>
<!--          <tr>
            <td class="tg-e3zv">Allahabad Bank</td>
            <td class="tg-031e"></td>
            </tr>-->
          <tr>
            <td class="tg-e3zv">Ludhiana Zone</td>
            <td class="tg-031e"><%= @quotation_detail.bankZoneOne.html_safe %></td>
          </tr>
          <tr>
            <td class="tg-e3zv">Amritsar Zone</td>
            <td class="tg-031e"><%= @quotation_detail.bankZoneTwo.html_safe %></td>
          </tr>
          <tr>
            <td class="tg-e3zv">Oriental Bank of Commerce</td>
            <td class="tg-031e"><%= @quotation_detail.bankNameTwo.html_safe %></td>
          </tr>
          <tr>
            <td class="tg-e3zv">Bank of Baroda</td>
            <td class="tg-031e"><%= @quotation_detail.bankNameThree.html_safe %></td>
          </tr>
          <tr>
            <td class="tg-e3zv">The Federal Bank Limited</td>
            <td class="tg-031e"><%= @quotation_detail.bankNameFour.html_safe %></td>
          </tr>
          <tr>
            <td class="tg-e3zv">Central Bank of India</td>
            <td class="tg-031e"><%= @quotation_detail.bankNameFive.html_safe %></td>
          </tr>
        </table>    
    </div>    
    <!--  Banks Names Start End -->    

        <!-- List of Gen Rates Start-->
    <div class="quotationsPdf" >
        <h4 class="quotationLinePdf"><%= @quotation_detail.quotationLine.html_safe  %></h4><br />
        <ul class="quotationsListPdf" style="list-style-type:none">
            <%= @quotation_detail.quotationRateList.html_safe  %>
        </ul> <br>
        <h5 class="serviceTaxPdf">*Service tax is applicable.</h5><br />
    </div>
    <!-- List of Gen Rates End -->
    <!-- Sender Details Start -->
    <div class="secondPageContentPdf">    
        <p class="contentPartOnePdf"><%= @quotation_detail.contentPartOne.html_safe %></p><br><br>
        <p class="contetnPartTwoPdf"><%= @quotation_detail.contentPartTwo.html_safe %></p><br><br>
        <p class="thankYouPdf"><%= @quotation_detail.thankYou.html_safe %></p><br><br>
        <p class="yoursTrulyPdf"><%= @quotation_detail.yoursTruly.html_safe  %></p><br><br>
        <p class="nameOfCompanyPdf"><%= @quotation_detail.nameOfCompany.html_safe  %></p><br><br><br>
        <p><%= image_tag(@sender_detail.signature.url(:med))%></p><br><br>
        <p class="namePdf"><%= @sender_detail.name.html_safe  %></p><hr class="nameHrLine"> 
    </div>       
    <!-- Sender Details End -->
    <!-- Template End -->
</section>

app/views/client_details/new.html.erb
<!-- CSS can be found in quotation.scss.css -->
<section class="quotationSection">
    <%= render "welcome/header"  %>
    <div class="quotationForm">
    <h2 class="fillForm">Client Details</h2>
      <%= form_for(@client_detail) do |f| %>

  <% if @client_detail.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @client_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
        <label class="ll">Designation</label><%= f.text_field :designation, autofocus: true, :required => true, :class => 'nameOfPerson', :placeholder => 'Designation',:title => 'Name of Person' %><br>
        <label class="ll">Bank Name</label><%= f.text_field :nameOfBank, autofocus: true, :required => true, :class => 'nameOfBank', :placeholder => 'Bank Name',:title => 'Name of Bank' %><br>
        <label class="ll">Address</label><%= f.text_field :address, autofocus: true, :required => true, :class => 'address', :placeholder => 'Address', :title => 'Address' %><br>
        <label class="ll">City</label><%= f.text_field :district, autofocus: true, :required => true, :class => 'district', :placeholder => 'District / City', :title => 'District / City' %><br>
        <label class="ll">Contact No.</label><%= f.text_field :contactNo, autofocus: true, :required => true, :class => 'contactNumber', :placeholder => 'Contact Number', :title => 'Contact Number' %><br>
        <label class="ll">Email</label> <%= f.email_field :emailID, autofocus: true, :required => true, :class => 'eMail', :placeholder => 'E-mail', :title => 'Email Id of Sender' %><br>
        <%= f.collection_select :sender_details_id, SenderDetail.all, :id, :name, prompt: true, autofocus: true, :required => true, :class => 'dropDown new-dropdown' %>
        <p style="text-align: center;"><%= f.submit :class => 'quotation_submit', :value => 'Submit', :disabled => false, :disable_with => "Please wait..." %></p><br>
      <% end %>
    </div> 
</section>

app/views/client_details/notice.html.erb
<h1>your mail has been sent </h1>

app/views/client_details/quotations.html.erb
<%= render 'welcome/header' %> <br><br><br><br><br>

<div class="container">
<table id="clients-quotations" class="display responsive no-wrap">
  <thead>
    <tr>
      <th>Reference Number</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Mail Status</th>
      <th>Mail Sent on </th>
    </tr>
  </thead>

  <tbody>
      <% @quotations.each do |q| %>
        <% if q.client_details_id == @client_details.id %>
        <tr>
     	    <td><%= q.referenceNumber %></td>
     	    <td><%= link_to "Show", quotation_detail_path(q.id) %></td>
          <td><%= link_to "Edit", "/editor" + quotation_detail_path(q.id) %></td>	
            <% if q.mailStatus == true %>               
              <td>Sent</td>
            <% else %>
	           <td>Draft</td>
            <% end %>
	 <td><%= q.dateOfMail %></td>
        </tr>    
	      <% end %>
      <% end %>
  </tbody>
</table>
</div>

<script>
    $(document).ready(function() {
    $('#clients-quotations').dataTable({
      responsive: true
    });
  } );
</script>