config/routes.rb
Rails.application.routes.draw do

  resources :bill_tables
  resources :guard_infos    
  resources :quotation_details
  resources :sender_details
  resources :gen_avails
  resources :gen_expenses
  resources :gen_details
  resources :third_party_providers
  resources :taxes

  root 'welcome#index'
  get  "dashboard"        => "client_details#dashboard"
  post "dashboard"	 => "client_details#dashboard"
  get  "client"           => "client_details#index"
  post "client"		        => "client_details#index"
  get  "clientdetails"    => "client_details#new"
  post "clientdetails"    => "client_details#new"
  get  "quotations/:id"   => "client_details#quotations"
  get "closed/client_details/:id" => "quotation_details#contractClose"
  get "opened/client_details/:id" => "quotation_details#contractOpen"
  post "closed/client_details/:id" => "quotation_details#contractClose"
  post "opened/client_details/:id" => "quotation_details#contractOpen"
  get  "sender"           => "sender_details#index"
  post "sender"		        => "sender_details#index"
  get  "senderdetails"    => "sender_details#new"
  post "senderdetails"    => "sender_details#new"
  get  "generators"       => "gen_details#index"
  get  "gendetails"       => "gen_details#new"
  post "gendetails"       => "gen_details#new"
  get  "genexpenses"      => "gen_expenses#index"
  get  "expenses"         => "gen_expenses#new" 
  post "expenses"         => "gen_expenses#new"  
  get  "quotationviewer"  => "quotation_details#index"
  get  "thirdparty"       => "third_party_providers#index"
  get  "providers"        => "third_party_providers#new"
  post "providers"        => "third_party_providers#new"
  get  "welcomemail"      => "client_details#mail"
  get  "sendpdfmail/:id"  => "quotation_details#mail"  
  get  "notice"           => "quotation_details#notice"
  get  "availableGenerators"     => "gen_avails#new"
  post "availableGenerators"     => "gen_avails#new"
  get  "/approved/quotation_details/:id" => "quotation_details#approve"
  post "/approved/quotation_details/:id" => "quotation_details#approve"

  devise_for :users
    as :user do
      get 'login'               => 'devise/sessions#new'
      post 'login'              => 'devise/sessions#create'
      get 'logout'              => 'devise/sessions#destroy'
      get 'register'            => 'devise/registrations#new'
      get 'registered'          => 'devise/registrations#show'
      get 'passwordReset'       => 'devise/passwords#new'
      get 'changePassword'      => 'devise/passwords#edit'  
      get 'resendConfirmation'  => 'devise/confirmations#new'    
    end

  mount Mercury::Engine => '/'

  resources :client_details do
    member { post :clientUpdate }
  end

  resources :fake_quotations do
    member { post :mercury_update}
  end

  namespace :mercury do
    resources :images
  end
 
  get "*path" => "quotation_details#notfound"      

end

app/models/bill_table.rb
class BillTable < ActiveRecord::Base
  belongs_to :quotation
end

app/models/client_detail.rb
class ClientDetail < ActiveRecord::Base
  belongs_to :sender_detail
  has_many :quotation

  
  validates_presence_of :contactNo
  validates_format_of :contactNo, with: /[0-9]/
  validates_length_of :contactNo, :maximum =>12, :minimum => 4

  validates_presence_of :sender_details_id
end

app/models/client_gen_set.rb
class ClientGenSet < ActiveRecord::Base
  belongs_to :quotation_detail
  belongs_to :client_detail
  belongs_to :gen_avail
  belongs_to :gaurd_detail
  belongs_to :third_party_gen
end

app/models/fake_quotation.rb
class FakeQuotation < ActiveRecord::Base
  belongs_to :client_details
  belongs_to :sender_details

  protokoll :referenceNumber, :pattern => "AEQF%y###"  
end

app/models/gaurd_detail.rb
class GaurdDetail < ActiveRecord::Base
end

app/models/gen_avail.rb
class GenAvail < ActiveRecord::Base

  validates_presence_of :gen_detail_id
  belongs_to :gen_detail
  protokoll :genID, :pattern => "G%y###"

end

app/models/gen_detail.rb
class GenDetail < ActiveRecord::Base
  
  validates_format_of :genRent, with: /[0-9]/, :message => "accepts Numbers only"
  validates_format_of :totalGen, with: /[0-9]/, :message => "accepts Numbers only"

  has_many :gen_avails	
end

app/models/gen_expense.rb
class GenExpense < ActiveRecord::Base
  belongs_to :client_detail
  
  validates_presence_of :readingBy
end

app/models/quotation_detail.rb
class QuotationDetail < ActiveRecord::Base
  belongs_to :client_detail
  belongs_to :sender_detail

  protokoll :referenceNumber, :pattern => "AE%y###"
end 

app/models/quotation_rent.rb
class QuotationRent < ActiveRecord::Base
  belongs_to :client_detail
  belongs_to :quotation_detail
end

app/models/sender_detail.rb
class SenderDetail < ActiveRecord::Base
  has_attached_file :signature, :styles => { :small => "150x150>", med: "200x200", large: "300x300"},
                    :url  => "/assets/sender_signature/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/sender_signature/:id/:style/:basename.:extension"
  validates_attachment_presence :signature
  validates_attachment :signature, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

 
  validates_presence_of :contactNo
  validates_format_of :contactNo, with: /[0-9]/
  validates_length_of :contactNo, :maximum =>12, :minimum => 4

  validates_presence_of :quotationType
end

app/models/tax.rb
class Tax < ActiveRecord::Base
end

app/models/third_party_gen.rb
class ThirdPartyGen < ActiveRecord::Base
  
  belongs_to :third_party_provider

  protokoll :genID, :pattern => "TP###"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
   def index
   end

   def mail
      QtMailer.qt_email().deliver	
   end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bill_tables_helper.rb
module BillTablesHelper
end

app/helpers/gen_avails_helper.rb
module GenAvailsHelper
end

app/helpers/gen_details_helper.rb
module GenDetailsHelper
end

app/helpers/gen_expenses_helper.rb
module GenExpensesHelper
end

app/helpers/taxes_helper.rb
module TaxesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_fakeQuotationHeader.html.erb
<header class="quotationHeader" id="quotationHeader" role="banner" style="display: block;">
    <nav class="navbar", role="navigation">
        <ul class="unlist1" >
            <li><%= link_to 'PDF', fake_quotation_path(@fake_quotation, format: 'pdf')%></li>
            <li><%= link_to "Edit Page", "/editor" + request.path, {:id => "edit_link"} %></li>
            <li ><%= link_to "DashBoard", dashboard_path %></li>
            <li ><%= link_to "Home", root_path %></li>        
            <li><%= link_to "Send Mail", "/sendpdfmail/" + @fake_quotation.id.to_s, {:id => "send_mail", :onclick => "loader();"} %></li>            
        </ul>
    </nav>  
</header>

<script type="text/javascript">
function loader(){
  $('.preloader').css("display","block");   
}
</script>        

app/views/welcome/_header.html.erb
<header class="header" id="header" role="banner" style="display: block;">
    <nav class="navbar", role="navigation">
        <ul class="unlist1">	
            <li ><%= link_to "Home", root_path %></li>	
            <li ><%= link_to "DashBoard", dashboard_path %></li>
            <% if user_signed_in? %>
                <li><%= link_to "Log Out", logout_path %></li>
            <% else %>       
                <li><%= link_to "Login", login_path %></li>
            <% end %>
        </ul>
    </nav>  
</header>

app/views/welcome/_quotationHeader.html.erb
<header class="quotationHeader" id="quotationHeader" role="banner" style="display: block;">
    <nav class="navbar", role="navigation">
        <ul class="unlist1" >
            <li ><%= link_to "Home", root_path %></li>
            <li ><%= link_to "DashBoard", dashboard_path %></li>
            <li><%= link_to "Edit Page", "/editor" + request.path, {:id => "edit_link"} %></li>
            <li><%= link_to "Send Mail", "/sendpdfmail/" + @quotation_detail.id.to_s, {:id => "send_mail", :onclick => "loader();"} %></li>
            <li><%= link_to 'PDF', quotation_detail_path(@quotation_detail, format: 'pdf')%></li>
        </ul>
    </nav>  
</header>

<script type="text/javascript">
function loader(){
	$('.preloader').css("display","block");		
}
</script>

app/views/welcome/index.html.erb
<section class="landingPage">    
    <div class="content">
        <h2 class="main-heading" id="main-heading">Amrit Engineering</h2><br>
        <h2 class="tagline1">Providing Generator</h2>
        <h2 class="tagline2">On</h2>
        <h2 class="tagline3">Rent Basis and Allied Services</h2>
        <p style="text-align: center;"><a href="/login"><button class="enter">Enter</button></a></p>
    </div> 
</section>

app/views/welcome/mail.html.erb
<h1>your email has been sent!</h1>