config/routes.rb
Rails.application.routes.draw do

  resources :bill_tables
  resources :guard_infos    
  resources :quotation_details
  resources :sender_details
  resources :gen_avails
  resources :gen_expenses
  resources :gen_details
  resources :third_party_providers
  resources :taxes

  root 'welcome#index'
  get  "dashboard"        => "client_details#dashboard"
  post "dashboard"	 => "client_details#dashboard"
  get  "client"           => "client_details#index"
  post "client"		        => "client_details#index"
  get  "clientdetails"    => "client_details#new"
  post "clientdetails"    => "client_details#new"
  get  "quotations/:id"   => "client_details#quotations"
  get "closed/client_details/:id" => "quotation_details#contractClose"
  get "opened/client_details/:id" => "quotation_details#contractOpen"
  post "closed/client_details/:id" => "quotation_details#contractClose"
  post "opened/client_details/:id" => "quotation_details#contractOpen"
  get  "sender"           => "sender_details#index"
  post "sender"		        => "sender_details#index"
  get  "senderdetails"    => "sender_details#new"
  post "senderdetails"    => "sender_details#new"
  get  "generators"       => "gen_details#index"
  get  "gendetails"       => "gen_details#new"
  post "gendetails"       => "gen_details#new"
  get  "genexpenses"      => "gen_expenses#index"
  get  "expenses"         => "gen_expenses#new" 
  post "expenses"         => "gen_expenses#new"  
  get  "quotationviewer"  => "quotation_details#index"
  get  "thirdparty"       => "third_party_providers#index"
  get  "providers"        => "third_party_providers#new"
  post "providers"        => "third_party_providers#new"
  get  "welcomemail"      => "client_details#mail"
  get  "sendpdfmail/:id"  => "quotation_details#mail"  
  get  "notice"           => "quotation_details#notice"
  get  "availableGenerators"     => "gen_avails#new"
  post "availableGenerators"     => "gen_avails#new"
  get  "/approved/quotation_details/:id" => "quotation_details#approve"
  post "/approved/quotation_details/:id" => "quotation_details#approve"

  devise_for :users
    as :user do
      get 'login'               => 'devise/sessions#new'
      post 'login'              => 'devise/sessions#create'
      get 'logout'              => 'devise/sessions#destroy'
      get 'register'            => 'devise/registrations#new'
      get 'registered'          => 'devise/registrations#show'
      get 'passwordReset'       => 'devise/passwords#new'
      get 'changePassword'      => 'devise/passwords#edit'  
      get 'resendConfirmation'  => 'devise/confirmations#new'    
    end

  mount Mercury::Engine => '/'

  resources :client_details do
    member { post :clientUpdate }
  end

  resources :fake_quotations do
    member { post :mercury_update}
  end

  namespace :mercury do
    resources :images
  end
 
  get "*path" => "quotation_details#notfound"      

end

app/models/bill_table.rb
class BillTable < ActiveRecord::Base
  belongs_to :quotation
end

app/models/client_detail.rb
class ClientDetail < ActiveRecord::Base
  belongs_to :sender_detail
  has_many :quotation

  
  validates_presence_of :contactNo
  validates_format_of :contactNo, with: /[0-9]/
  validates_length_of :contactNo, :maximum =>12, :minimum => 4

  validates_presence_of :sender_details_id
end

app/models/client_gen_set.rb
class ClientGenSet < ActiveRecord::Base
  belongs_to :quotation_detail
  belongs_to :client_detail
  belongs_to :gen_avail
  belongs_to :gaurd_detail
  belongs_to :third_party_gen
end

app/models/fake_quotation.rb
class FakeQuotation < ActiveRecord::Base
  belongs_to :client_details
  belongs_to :sender_details

  protokoll :referenceNumber, :pattern => "AEQF%y###"  
end

app/models/gaurd_detail.rb
class GaurdDetail < ActiveRecord::Base
end

app/models/gen_avail.rb
class GenAvail < ActiveRecord::Base

  validates_presence_of :gen_detail_id
  belongs_to :gen_detail
  protokoll :genID, :pattern => "G%y###"

end

app/models/gen_detail.rb
class GenDetail < ActiveRecord::Base
  
  validates_format_of :genRent, with: /[0-9]/, :message => "accepts Numbers only"
  validates_format_of :totalGen, with: /[0-9]/, :message => "accepts Numbers only"

  has_many :gen_avails	
end

app/models/gen_expense.rb
class GenExpense < ActiveRecord::Base
  belongs_to :client_detail
  
  validates_presence_of :readingBy
end

app/models/quotation_detail.rb
class QuotationDetail < ActiveRecord::Base
  belongs_to :client_detail
  belongs_to :sender_detail

  protokoll :referenceNumber, :pattern => "AE%y###"
end 

app/models/quotation_rent.rb
class QuotationRent < ActiveRecord::Base
  belongs_to :client_detail
  belongs_to :quotation_detail
end

app/models/sender_detail.rb
class SenderDetail < ActiveRecord::Base
  has_attached_file :signature, :styles => { :small => "150x150>", med: "200x200", large: "300x300"},
                    :url  => "/assets/sender_signature/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/sender_signature/:id/:style/:basename.:extension"
  validates_attachment_presence :signature
  validates_attachment :signature, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

 
  validates_presence_of :contactNo
  validates_format_of :contactNo, with: /[0-9]/
  validates_length_of :contactNo, :maximum =>12, :minimum => 4

  validates_presence_of :quotationType
end

app/models/tax.rb
class Tax < ActiveRecord::Base
end

app/models/third_party_gen.rb
class ThirdPartyGen < ActiveRecord::Base
  
  belongs_to :third_party_provider

  protokoll :genID, :pattern => "TP###"

end

app/models/third_party_provider.rb
class ThirdPartyProvider < ActiveRecord::Base

  validates_presence_of :contactNo
  validates_format_of :contactNo, with: /[0-9]/
  validates_length_of :contactNo, :maximum =>12, :minimum => 4

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/gen_avails_controller.rb
class GenAvailsController < ApplicationController
  before_action :set_gen_avail, only: [:show, :edit, :update, :destroy]

  # GET /gen_avails
  # GET /gen_avails.json
  def index
    @gen_avails = GenAvail.all
  end

  # GET /gen_avails/1
  # GET /gen_avails/1.json
  def show
  end

  # GET /gen_avails/new
  def new
    @gen_avail = GenAvail.new
  end

  # GET /gen_avails/1/edit
  def edit
	@detail = GenDetail.find(params[:id])
  end

  # POST /gen_avails
  # POST /gen_avails.json
  def create
    @gen_avail = GenAvail.new(gen_avail_params)

    respond_to do |format|
      if @gen_avail.save
        format.html { redirect_to gen_details_path }
#        format.html { redirect_to @gen_avail, notice: 'Gen avail was successfully created.' }
#        format.json { render :index, status: :created, location: gen_detail_path }
      else
        format.html { render :new }
        format.json { render json: @gen_avail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gen_avails/1
  # PATCH/PUT /gen_avails/1.json
  def update
    respond_to do |format|
      if @gen_avail.update(gen_avail_params)
        format.html { redirect_to gen_details_path }
#        format.html { redirect_to @gen_avail, notice: 'Gen avail was successfully updated.' }
#        format.json { render :show, status: :ok, location: @gen_avail }
      else
        format.html { render :edit }
        format.json { render json: @gen_avail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gen_avails/1
  # DELETE /gen_avails/1.json
  def destroy
    @gen_avail.destroy
    respond_to do |format|
      format.html { redirect_to gen_details_path }
#      format.html { redirect_to gen_avails_url, notice: 'Gen avail was successfully destroyed.' }
#      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gen_avail
      @gen_avail = GenAvail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gen_avail_params
	
    params.require(:gen_avail).permit(:gen_detail_id, :genID, :available)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bill_tables_helper.rb
module BillTablesHelper
end

app/helpers/gen_avails_helper.rb
module GenAvailsHelper
end

app/helpers/gen_details_helper.rb
module GenDetailsHelper
end

app/helpers/gen_expenses_helper.rb
module GenExpensesHelper
end

app/helpers/taxes_helper.rb
module TaxesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gen_avails/_form.html.erb
<%= form_for(@gen_avail) do |f| %>
  <% if @gen_avail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gen_avail.errors.count, "error") %> prohibited this gen_avail from being saved:</h2>

      <ul>
      <% @gen_avail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<br>Generator Type: <%= @detail.genType %><br />
  Generator Name(Unique) <%= f.text_field :genID, :readonly => true %><br />
	Available <%= f.check_box :available %><br />

	<%= f.submit %>
<% end %>

app/views/gen_avails/edit.html.erb
<%= render 'welcome/header' %> <br>
<section class="quotationSection">
    <div class="quotationForm">
    <h2 class="fillForm">Editing Generator Availability</h2>


<%= link_to 'Back', gen_details_path %>

<%= render 'form' %>

    </div> 
</section>

app/views/gen_avails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Gen Avails</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gen_avails.each do |gen_avail| %>
      <tr>
	<td><%= gen_avail.genID %></td>
        <td><%= link_to 'Show', gen_avail %></td>
        <td><%= link_to 'Edit', edit_gen_avail_path(gen_avail) %></td>
        <td><%= link_to 'Destroy', gen_avail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gen avail', new_gen_avail_path %>

app/views/gen_avails/new.html.erb
<%= render "welcome/header" %> <br><br><br><br><br>
<h1 class="genAvailHeading">Available Generators</h1><br> <br>

<%= form_for(@gen_avail) do |f| %>
  <% if @gen_avail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gen_avail.errors.count, "error") %> prohibited this gen_avail from being saved:</h2>
        
      <ul>
      <% @gen_avail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">

  <p style="text-align:center;"><%= f.collection_select :gen_detail_id, GenDetail.all, :id, :genType, prompt: true, :class => 'dropDown' %></p><br />
  <p style="text-align:center;"> Available : <%= f.check_box :available %></p><br />
  <p style="text-align:center;"><%= submit_tag "Submit", :id => "submit", :name => "submit", :class => "form_submit", :disabled => false, :disable_with => "Please wait..." %>
  </p>
  </div>
<% end %>

app/views/gen_avails/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_gen_avail_path(@gen_avail) %> |
<%= link_to 'Back', gen_avails_path %>